export enum brandIndustry {
  TELECOMMUNICATIONS = 'telecommunications',
  FASHION = 'fashion',
  BEAUTY_AND_CARE = 'beauty and care',
  ADVERTISING_AND_MARKETING = 'advertising and marketing',
  CONSTRUCTION = 'construction',
  SOFTWARE_DEVELOPMENT = 'software development',
  FINANCE = 'finance',
  HEALTHCARE = 'healthcare',
  EDUCATION = 'education',
  AUTOMOTIVE = 'automotive',
  FOOD_AND_BEVERAGE = 'food and beverage',
  RETAIL = 'retail',
  MANUFACTURING = 'manufacturing',
  TRAVEL_AND_TOURISM = 'travel and tourism',
  ENTERTAINMENT = 'entertainment',
  ENERGY = 'energy',
  REAL_ESTATE = 'real estate',
  TRANSPORTATION = 'transportation',
  AGRICULTURE = 'agriculture',
  PHARMACEUTICALS = 'pharmaceuticals'
}
